name: basic_trie
description: A simple trie implementation in Dart.
version: 1.5.0
homepage: https://github.com/flutter-cavalry/basic_trie

environment:
  sdk: ">=2.18.6 <4.0.0"

dev_dependencies:
  lints: ^5.0.0
  test: ^1.16.0
